    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script> 
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
    <script type="text/javascript">
	function getURLParameter(name) {
		return decodeURIComponent(
			(RegExp(name + '=' + '(.+?)(&|$)').exec(location.search)||[,null])[1]
		);
	}
    $(document).ready(function() { 
		var latlng = new google.maps.LatLng(getURLParameter('lat'),getURLParameter('lon'));
                var image = '<?php echo $this->getSkinUrl('images/raveinfosys/dealer/google_maps/marker.png') ?>';
		var options = {
			zoom: 12,
			center: latlng,
			mapTypeId: google.maps.MapTypeId.ROADMAP //SATELLITE
		};
		map = new google.maps.Map(document.getElementById("map_canvas"), options);
		geocoder = new google.maps.Geocoder();
		var infowindow = new google.maps.InfoWindow({
			content: getURLParameter('address')
		});
                
		marker = new google.maps.Marker({
			map: map,
			draggable: false,
                        position: new google.maps.LatLng(getURLParameter('lat'), getURLParameter('lon')),
                        icon: image
		});
		google.maps.event.addListener(marker, 'click', function() {
			infowindow.open(map,marker);
		});
                infowindow.open(map,marker);
	});
    </script> 
    <div id="map_canvas"></div><br/> 
    <style>
        #map_canvas{width:80%; height:500px; margin:0px auto;}
        
        @media only screen and (max-width: 767px) {
           #map_canvas{width:100%; height:200px; margin:0px auto;} 
        } 
    </style>